version: 1.2.2#{build}
image: Visual Studio 2017
platform: Any CPU
skip_tags: true
configuration: Release
install:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init --recursive

    nuget restore HackusMailCheckerReforged.sln
before_build:
  - ps: ${env:REV} = (git rev-list --count HEAD)
build:
  verbosity: normal
after_build:
- cmd: >-
    move %APPVEYOR_BUILD_FOLDER%\Hackus-Mail-Checker-Reforged\bin\release\chromedriver.exe %APPVEYOR_BUILD_FOLDER%\Hackus-Mail-Checker-Reforged\bin\release\bin\

    move %APPVEYOR_BUILD_FOLDER%\Hackus-Mail-Checker-Reforged\bin\release\geckodriver.exe %APPVEYOR_BUILD_FOLDER%\Hackus-Mail-Checker-Reforged\bin\release\bin\

    7z a Hackus-Mail-Checker-Reforged.zip %APPVEYOR_BUILD_FOLDER%\Hackus-Mail-Checker-Reforged\bin\release\
artifacts:
- path: Hackus-Mail-Checker-Reforged.zip
  name: Hackus-Mail-Checker-Reforged
deploy:  
  - provider: GitHub
    artifact: /.*\.zip/
    tag: 1.2.2#$(REV)
    force_update: true
    auth_token:
        secure: YD1leHIRRO+gvFbGjjLxdvUb/iL3pYR3/Edalpxr1RdKzsLbfMf6YHEI2Uum6qbM
    on:
      branch: master
