version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - msbuild MySolution.sln

test_script:
  - nunit-console MyProject.Tests.dll

deploy:
  provider: GitHub
  auth_token:
    secure: your_encrypted_token
  release: my_tag
  artifact: path/to/your/artifact
