version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - Hackus Mail Checker Reforged.sln

deploy:
  provider: GitHub
  auth_token:
    secure: your_encrypted_token
  release: my_tag
  artifact: path/to/your/artifact
