version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - Hackus Mail Checker Reforged.sln

deploy:
  provider: GitHub
  auth_token:
    secure: YD1leHIRRO+gvFbGjjLxdvUb/iL3pYR3/Edalpxr1RdKzsLbfMf6YHEI2Uum6qbM
  release: my_tag
  artifact: path/to/your/artifact
